export const books = [
    {
        id: 1,
        title: 'The Great Gatsby',
        author: 'F. Scott Fitzgerald',
        price: 12.99,
        category: 'Fiction',
        image: '/placeholder.svg',
    },
    {
        id: 2,
        title: 'To Kill a Mockingbird',
        author: 'Harper Lee',
        price: 9.99,
        category: 'Fiction',
        image: '/placeholder.svg',
    },
    {
        id: 3,
        title: 'Atomic Habits',
        author: 'James Clear',
        price: 15.99,
        category: 'Self-Help',
        image: '/placeholder.svg',
    },
    {
        id: 4,
        title: 'The Alchemist',
        author: 'Paulo Coelho',
        price: 8.99,
        category: 'Fiction',
        image: '/placeholder.svg',
    },
    {
        id: 5,
        title: 'Educated',
        author: 'Tara Westover',
        price: 13.99,
        category: 'Memoir',
        image: '/placeholder.svg',
    },
    {
        id: 6,
        title: 'Sapiens',
        author: 'Yuval Noah Harari',
        price: 17.99,
        category: 'History',
        image: '/placeholder.svg',
    },
    {
        id: 7,
        title: 'The Subtle Art of Not Giving a F*ck',
        author: 'Mark Manson',
        price: 11.99,
        category: 'Self-Help',
        image: '/placeholder.svg',
    },
    {
        id: 8,
        title: 'The Kite Runner',
        author: 'Khaled Hosseini',
        price: 10.99,
        category: 'Fiction',
        image: '/placeholder.svg',
    },
    {
        id: 9,
        title: 'Becoming',
        author: 'Michelle Obama',
        price: 14.99,
        category: 'Memoir',
        image: '/placeholder.svg',
    },
    {
        id: 10,
        title: 'The Immortal Life of Henrietta Lacks',
        author: 'Rebecca Skloot',
        price: 12.99,
        category: 'Non-Fiction',
        image: '/placeholder.svg',
    },
    {
        id: 11,
        title: "The Handmaid's Tale",
        author: 'Margaret Atwood',
        price: 9.99,
        category: 'Fiction',
        image: '/placeholder.svg',
    },
    {
        id: 12,
        title: 'Daring Greatly',
        author: 'Brené Brown',
        price: 13.99,
        category: 'Self-Help',
        image: '/placeholder.svg',
    },
];

export const CLOUDNAME = import.meta.env.VITE_CLOUDNAME;
export const cloudinaryUploadPreset = import.meta.env.VITE_UPLOADPRESET;
export const IMAGEUPLOADCONFIG = {
    cloudName: CLOUDNAME,
    uploadPreset: cloudinaryUploadPreset,
    resourceType: 'image',
    cropping: true,
    croppingCoordinatesMode: 'custom',
    croppingAspectRatio: 2 / 3,
    croppingDefaultSelectionRatio: 100 / 150,
    showSkipCropButton: false,
    clientAllowedFormats: ['jpg', 'jpeg', 'png', 'webp'],
};

export const BASE_URL = 'http://localhost:3000/api';
